'use strict';
const panel=document.getElementById('contentPanel'),welcome=document.getElementById('welcomeText'),notice=document.getElementById('completionNotice');let me=null;
function safe(v){return String(v??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
async function json(url, opts){const r=await fetch(url,opts);return r.json()}
function completion(user){const p=user?.profile||{};let points=0,total=7;if(user?.name)points++;if(p.birthDate)points++;if(p.birthTime)points++;if(p.height)points++;if(p.zodiac)points++;if(user?.echoProfile?.answers?.length)points++;if((p.photos||[]).length)points++;return Math.round(points/total*100)}
async function loadMe(){try{const d=await json('/api/me');if(!d.user){location.href='../auth/';return;}me=d.user;const pct=completion(me);welcome.textContent=`Welcome, ${me.name}. This is your Echo AI Twin center: tasks, Soul Map, probabilities and profile progress.`;notice.textContent=`Profile completion: ${pct}% — finish your 100 Echo questions to unlock deeper AI Twin tasks.`;renderProfile();}catch(e){welcome.textContent='Start with npm run dev. /api/me not available.'}}
function renderProfile(){const p=me.profile||{};panel.innerHTML=`<h2>Your current profile</h2><div class="panel-grid"><div class="info-card"><b>Name</b>${safe(me.name)}</div><div class="info-card"><b>Email</b>${safe(me.email)}</div><div class="info-card"><b>Height</b>${safe(p.height||'not added')}m</div><div class="info-card"><b>Birth</b>${safe(p.birthDate||'missing')} ${safe(p.birthTime||'')}</div><div class="info-card"><b>Zodiac</b>${safe(p.zodiac||'auto pending')}</div><div class="info-card"><b>Echo</b>${safe(me.echoProfile?.result?.type||'not finished')}</div></div>`;}
async function renderTasks(){const d=await json('/api/tasks');panel.innerHTML='<h2>Echo Tasks</h2><div class="panel-grid">'+(d.tasks||[]).map(t=>`<div class="info-card"><b>${safe(t.title)}</b><p>${safe(t.text)}</p><small>${safe(t.status)}</small></div>`).join('')+'</div>'}
async function renderProb(){const d=await json('/api/probabilities');panel.innerHTML='<h2>Probabilities</h2><p>Generated from your base info, zodiac, Echo answers and anonymous user patterns.</p><div class="panel-grid">'+Object.entries(d.probabilities||{}).map(([k,v])=>`<div class="info-card"><b>${safe(k)}</b>${safe(v)}%</div>`).join('')+'</div>'}
async function renderMemories(){const d=await json('/api/live-updates?range=7d');panel.innerHTML='<h2>Live Memories / News</h2><div class="panel-grid">'+(d.updates||[]).map(u=>`<div class="info-card"><b>${safe(u.city||'Around')}</b><p>${safe(u.text)}</p><small>${safe(u.status)} · ${safe(u.visibility)}</small></div>`).join('')+'</div>'}
document.querySelectorAll('[data-action]').forEach(btn=>btn.onclick=async()=>{const a=btn.dataset.action;if(a==='questions')location.href='../echo-questions/full-100/';if(a==='aiworld')document.getElementById('aiWorld').scrollIntoView({behavior:'smooth'});if(a==='tasks')renderTasks();if(a==='soulmap')location.href='../member-zodiac/';if(a==='probabilities')renderProb();if(a==='memories')renderMemories();if(a==='coming')panel.innerHTML='<h2>Coming Soon!</h2><p>More AI Twin options are locked for the next build.</p>';if(a==='logout'){await json('/api/logout',{method:'POST'});location.href='../home/';}});
// background
const c=document.getElementById('twinCanvas'),ctx=c.getContext('2d');let stars=[];function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;stars=Array.from({length:innerWidth<760?350:700},()=>({x:Math.random()*c.width,y:Math.random()*c.height,r:Math.random()*1.8+.3,v:Math.random()*.12+.03}))}addEventListener('resize',resize);resize();function loop(){ctx.clearRect(0,0,c.width,c.height);const g=ctx.createRadialGradient(c.width*.3,c.height*.2,0,c.width*.5,c.height*.55,c.width*.8);g.addColorStop(0,'rgba(255,82,190,.22)');g.addColorStop(.45,'rgba(56,203,255,.12)');g.addColorStop(1,'#050713');ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height);stars.forEach(s=>{s.y+=s.v;if(s.y>c.height)s.y=0;ctx.fillStyle='rgba(255,255,255,.72)';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()});requestAnimationFrame(loop)}loop();loadMe();
